// Mock data for frontend development
export const mockMenuItems = [
  // Hot Drinks
  {
    id: 1,
    name: "Buna (Coffee)",
    nameOm: "Buna (Qaawa)",
    description: "Traditional Ethiopian coffee served with popcorn",
    descriptionOm: "Buna aadaa Ethiopia kan baqlo waliin tajaajilamu",
    price: 89,
    original_price: null,
    category: "hot_drink",
    image_url: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=400",
    is_available: true,
    preparation_time: 15,
    spicy_level: 0,
    rating: 4.9,
    ingredients: ["Ethiopian Coffee Beans", "Water"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free"],
    allergens: [],
    nutrition: { calories: "5", protein: "0g", carbs: "0g", fat: "0g" }
  },
  {
    id: 2,
    name: "Tea (Shai)",
    nameOm: "Shaayi",
    description: "Hot tea with spices",
    descriptionOm: "Shaayi ho'aa foolii qabu",
    price: 49,
    original_price: null,
    category: "hot_drink",
    image_url: "https://images.unsplash.com/photo-1563720372004-c5090b8a2fe3?w=400",
    is_available: true,
    preparation_time: 5,
    spicy_level: 0,
    rating: 4.7,
    ingredients: ["Tea Leaves", "Water", "Spices"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free"],
    allergens: [],
    nutrition: { calories: "2", protein: "0g", carbs: "0g", fat: "0g" }
  },
  // Breakfast
  {
    id: 3,
    name: "Chechebsa (Kita Firfir)",
    nameOm: "Cecebsa",
    description: "Shredded flatbread with spiced butter",
    descriptionOm: "Maxinoo ittoo bullaa'een qophaa'ee",
    price: 149,
    original_price: null,
    category: "breakfast",
    image_url: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=400",
    is_available: true,
    preparation_time: 20,
    spicy_level: 2,
    rating: 4.8,
    ingredients: ["Flatbread", "Spiced Butter", "Berbere"],
    dietary_tags: ["vegetarian"],
    allergens: ["gluten", "dairy"],
    nutrition: { calories: "450", protein: "8g", carbs: "45g", fat: "25g" }
  },
  // Marqaa
  {
    id: 4,
    name: "Marqaa (Porridge)",
    nameOm: "Marqaa",
    description: "Traditional Ethiopian porridge with milk and honey",
    descriptionOm: "Marqaa aadaa Ethiopia annanii fi damma waliin",
    price: 129,
    original_price: null,
    category: "marqaa",
    image_url: "https://images.unsplash.com/photo-1517672651696-24815e206b2c?w=400",
    is_available: true,
    preparation_time: 15,
    spicy_level: 0,
    rating: 4.6,
    ingredients: ["Barley Flour", "Milk", "Honey", "Butter"],
    dietary_tags: ["vegetarian"],
    allergens: ["gluten", "dairy"],
    nutrition: { calories: "320", protein: "8g", carbs: "55g", fat: "8g" }
  },
  // Traditional Food
  {
    id: 5,
    name: "Doro Wat",
    nameOm: "Doro Wat",
    description: "Spicy chicken stew with egg",
    descriptionOm: "Ittoo daangaa'aa waan hanqaaquu qabu",
    price: 299,
    original_price: null,
    category: "traditional_food",
    image_url: "https://images.unsplash.com/photo-1612033721492-d4f813c012e5?w=400",
    is_available: true,
    preparation_time: 45,
    spicy_level: 3,
    rating: 5.0,
    ingredients: ["Chicken", "Berbere", "Onions", "Garlic", "Egg", "Spiced Butter"],
    dietary_tags: ["gluten-free"],
    allergens: ["eggs", "dairy"],
    nutrition: { calories: "580", protein: "35g", carbs: "15g", fat: "40g" }
  },
  {
    id: 6,
    name: "Kitfo",
    nameOm: "Kitfo",
    description: "Minced raw beef with mitmita and kibe",
    descriptionOm: "Fo'on qeccaa'aa waan mitmiitaa fi qibe qabu",
    price: 349,
    original_price: null,
    category: "traditional_food",
    image_url: "https://images.unsplash.com/photo-1561982963-d6b7b5b8b00c?w=400",
    is_available: true,
    preparation_time: 30,
    spicy_level: 3,
    rating: 4.9,
    ingredients: ["Raw Beef", "Mitmita", "Kibe (Spiced Butter)", "Kocho", "Ayeb (Cheese)"],
    dietary_tags: ["gluten-free"],
    allergens: ["dairy"],
    nutrition: { calories: "620", protein: "42g", carbs: "8g", fat: "45g" }
  },
  // Pizza
  {
    id: 7,
    name: "Margherita Pizza",
    nameOm: "Piizaa Maargiiriitaa",
    description: "Fresh mozzarella, tomato sauce, basil",
    descriptionOm: "Moozarellaa haaraa, ittoo timaatimii, baazilii",
    price: 899,
    original_price: 1099,
    category: "pizza",
    image_url: "https://images.unsplash.com/photo-1604382355076-af4b0eb60143?w=400",
    is_available: true,
    preparation_time: 20,
    spicy_level: 0,
    rating: 4.8,
    ingredients: ["Fresh Mozzarella", "Tomato Sauce", "Basil", "Olive Oil"],
    dietary_tags: ["vegetarian"],
    allergens: ["gluten", "dairy"],
    nutrition: { calories: "850", protein: "32g", carbs: "95g", fat: "28g" }
  },
  // Burger
  {
    id: 8,
    name: "Classic Cheeseburger",
    nameOm: "Baagarii kiisii kan sadaqqaa",
    description: "Beef patty with cheese, lettuce, tomato",
    descriptionOm: "Fo'on foon qaamaa waan qincee, salaatii, timaatiimi fi qeccaa qabu",
    price: 399,
    original_price: null,
    category: "burger",
    image_url: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400",
    is_available: true,
    preparation_time: 15,
    spicy_level: 1,
    rating: 4.7,
    ingredients: ["Beef Patty", "Cheese", "Lettuce", "Tomato", "Pickles", "Bun"],
    dietary_tags: [],
    allergens: ["gluten", "dairy", "eggs"],
    nutrition: { calories: "750", protein: "35g", carbs: "45g", fat: "45g" }
  },
  // Sandwich
  {
    id: 9,
    name: "Club Sandwich",
    nameOm: "Sandwiichii Kaalaabii",
    description: "Triple decker with chicken, bacon, lettuce, tomato",
    descriptionOm: "Lallaabaa sadii waan lukkuu, beekonii, salaatii fi timaatiimiin",
    price: 349,
    original_price: null,
    category: "sandwich",
    image_url: "https://images.unsplash.com/photo-1553909489-cb47b5cbe33a?w=400",
    is_available: true,
    preparation_time: 12,
    spicy_level: 0,
    rating: 4.6,
    ingredients: ["Chicken", "Bacon", "Lettuce", "Tomato", "Mayo", "Toast"],
    dietary_tags: [],
    allergens: ["gluten", "dairy", "eggs"],
    nutrition: { calories: "680", protein: "38g", carbs: "52g", fat: "38g" }
  },
  // Traditional Drink
  {
    id: 10,
    name: "Tej (Honey Wine)",
    nameOm: "Tejii (Daadhii)",
    description: "Traditional Ethiopian honey wine",
    descriptionOm: "Daadhii aadaa Ethiopia",
    price: 199,
    original_price: null,
    category: "traditional_drink",
    image_url: "https://images.unsplash.com/photo-1535991280070-e7ebbe3f7cc7?w=400",
    is_available: true,
    preparation_time: 5,
    spicy_level: 0,
    rating: 4.8,
    ingredients: ["Honey", "Water", "Gesho"],
    dietary_tags: ["vegan", "gluten-free"],
    allergens: [],
    nutrition: { calories: "150", protein: "0g", carbs: "12g", fat: "0g" }
  },
  // Juice
  {
    id: 11,
    name: "Fresh Orange Juice",
    nameOm: "Juucii Birtukaanii Haaraa",
    description: "Freshly squeezed orange juice",
    descriptionOm: "Juucii birtukaanii haaraa",
    price: 99,
    original_price: null,
    category: "juice",
    image_url: "https://images.unsplash.com/photo-1613478223719-2ab802602423?w=400",
    is_available: true,
    preparation_time: 5,
    spicy_level: 0,
    rating: 4.9,
    ingredients: ["Fresh Oranges"],
    dietary_tags: ["vegan", "gluten-free", "dairy-free"],
    allergens: [],
    nutrition: { calories: "110", protein: "2g", carbs: "26g", fat: "0g" }
  },
  // Soft Drink
  {
    id: 12,
    name: "Coca Cola",
    nameOm: "Kookii Koolaa",
    description: "Refreshing cola drink",
    descriptionOm: "Dhugaatii koolaa qorraa",
    price: 49,
    original_price: null,
    category: "softdrink",
    image_url: "https://images.unsplash.com/photo-1581006852262-e4307cf6283a?w=400",
    is_available: true,
    preparation_time: 2,
    spicy_level: 0,
    rating: 4.5,
    ingredients: ["Carbonated Water", "Sugar", "Caffeine"],
    dietary_tags: ["vegan", "gluten-free"],
    allergens: [],
    nutrition: { calories: "140", protein: "0g", carbs: "39g", fat: "0g" }
  }
];

export const mockCategories = [
  "hot_drink",
  "breakfast", 
  "marqaa",
  "food",
  "lunch",
  "dinner",
  "burger",
  "pizza",
  "traditional_food",
  "traditional_drink",
  "sandwich",
  "juice",
  "softdrink"
];

export const mockQRCodes = [
  {
    id: 1,
    name: "ዋና ምናሌ",
    short_id: "main-menu",
    target_url: "https://yourdomain.com/q/main-menu",
    is_active: true,
    scan_count: 245,
    created_at: new Date().toISOString()
  }
];
